/**
 * Pure logic for Peter's Watch: which apostle responds to a given message,
 * and whether the message itself is a crisis that should bypass Claude
 * entirely. Kept dependency-free (no Firestore, no Anthropic SDK) so it can
 * be unit-tested directly and reused by the API route without pulling in
 * either.
 */
import { APOSTLES, type ApostleId } from "@/lib/apostles";

// First-layer, deterministic safety net — checked before any LLM call.
// Intentionally broad rather than clever: a false positive just means a
// caring, human-directing reply where casual conversation would have done;
// a false negative is the real risk. The system prompt is the second layer
// for phrasing this list misses.
const CRISIS_PATTERNS: RegExp[] = [
  /\bsuicid(e|al)\b/i,
  /\bkill(ing)?\s+myself\b/i,
  /\bend(ing)?\s+(it all|my life)\b/i,
  /\bwant(ing)?\s+to\s+die\b/i,
  /\bwish\s+i\s+(was|were)n'?t\s+alive\b/i,
  /\bself[\s-]?harm(ing)?\b/i,
  /\bhurt(ing)?\s+myself\b/i,
  /\bcutting\s+myself\b/i,
  /\bno\s+reason\s+to\s+live\b/i,
  /\bbetter\s+off\s+dead\b/i,
  /\bcan'?t\s+go\s+on\b/i,
  /\bdon'?t\s+want\s+to\s+be\s+here\s+anymore\b/i,
];

export function isCrisisMessage(text: string): boolean {
  return CRISIS_PATTERNS.some((pattern) => pattern.test(text));
}

/** A fixed, carefully-worded response — never generated by the model — for
 * when isCrisisMessage() fires. Always "spoken" by Peter, Davar's default
 * companion, so it reads as continuous with the conversation rather than a
 * jarring system message. */
export const CRISIS_RESPONSE =
  "I hear real pain in what you just said, and I don't want to talk past it. " +
  "You matter too much for that. Please reach out to someone who can be with you right now — " +
  "a friend, a pastor, or a crisis line. In the US, you can call or text 988 (the Suicide & Crisis Lifeline) any time, day or night. " +
  "Outside the US, findahelpline.com can point you to one near you. " +
  "I'm still here whenever you want to talk — but this is bigger than our chat, and you shouldn't carry it alone.";

const DOUBT_PATTERNS: RegExp[] = [
  /\bdoubt(ing|s|ful)?\b/i,
  /\bdiscourag(ed|ing|ement)\b/i,
  /\bgiv(e|ing)\s+up\b/i,
  /\bhopeless\b/i,
  /\bpointless\b/i,
  /\bwhat'?s\s+the\s+point\b/i,
  /\bgod\s+(doesn'?t|isn'?t|won'?t)\b/i,
  /\b(don'?t|do\s+not)\s+know\s+if\s+god\b/i,
  /\bfeel\s+far\s+from\s+god\b/i,
  /\bcan'?t\s+do\s+this\b/i,
  /\bnothing'?s?\s+working\b/i,
  /\bnot\s+sure\s+(i|I)\s+believe\b/i,
  /\bfeel(ing)?\s+stuck\b/i,
];

const ENCOURAGEMENT_PATTERNS: RegExp[] = [
  /\bgrateful\b/i,
  /\bthankful\b/i,
  /\bproud\s+of\s+myself\b/i,
  /\bgood\s+day\b/i,
  /\bfeel(ing)?\s+strong\b/i,
  /\bkept?\s+my\s+streak\b/i,
  /\bstayed\s+(strong|clean|faithful)\b/i,
  /\bresisted\b/i,
  /\bwon\s+today\b/i,
  /\bexcited\b/i,
  /\bfeeling\s+good\b/i,
  /\bmade\s+it\s+through\b/i,
];

/**
 * Decides which apostle responds to a user's message. Simple, ordered
 * keyword checks — good enough for v1 per the spec, doesn't need to be
 * perfect. Doubt/discouragement is checked first (it's the more urgent
 * signal), then encouragement-worthy positivity, and Peter is the default
 * for everything else, especially accountability-specific content.
 */
export function routeApostle(text: string): ApostleId {
  if (DOUBT_PATTERNS.some((pattern) => pattern.test(text))) return "thomas";
  if (ENCOURAGEMENT_PATTERNS.some((pattern) => pattern.test(text))) return "john";
  return "peter";
}

const SHARED_GUIDELINES = `
Guidelines, always:
- Keep replies short and warm — 2 to 5 sentences, like a real text message, never an essay or a sermon.
- Never shame, lecture, or moralize. Never imply the user is disqualified, dirty, or beyond grace.
- Never diagnose a mental health condition, and never speak with clinical or medical authority.
- Always point back to grace and toward one concrete, small next step — not just feelings, something to actually do today.
- If asked directly whether you're a real person, answer honestly: you're an AI companion voicing this apostle's perspective inside the Davar app, not a real human, pastor, or licensed counselor.
- If anything in the user's message suggests real crisis (self-harm, suicidal thoughts, wanting to die), set the normal conversation aside and warmly, directly encourage them to reach out to a real person or a crisis line right now (in the US, 988) — that matters more than continuing as usual.`;

/** How many user messages Peter's Watch will answer per calendar day —
 * generous (not a stingy trickle) while keeping API cost predictable.
 * Enforced server-side via a per-user-per-day Firestore counter (see
 * watch_chat_usage in src/types/firestore.ts), the same pattern as the
 * free-tier daily lesson cap. Crisis messages (see isCrisisMessage above)
 * are exempt — safety never waits on a quota. */
export const WATCH_CHAT_DAILY_LIMIT = 15;

// In-character closes for when the daily limit is hit, instead of a
// generic rate-limit error. Written in whichever apostle's voice is
// currently responding (see routeApostle) so it reads as part of the
// conversation, not a system interruption — deliberately warm, not final:
// it always promises a return.
const CLOSING_MESSAGES: string[] = [
  "I need to go now — there's someone else waiting on me. But I'll be here again tomorrow. Until then, hold onto what we talked about today. Grace carries you further than willpower ever will.",
  "That's enough for today, my friend. Go rest in what's already true of you — you don't have to earn tomorrow's mercy, it's already waiting. I'll be right here when you come back.",
  "I have to step away for now, but you're not carrying this alone tonight. Sleep well. Tomorrow is a new mercy, and so am I — waiting for you, same as always.",
  "Our time's up for today, but don't let that trouble you. What you shared here mattered. Come find me again tomorrow — I'm not going anywhere.",
];

/** Randomly selects one of the closing-conversation variations. Called
 * once, when the daily limit is actually hit, and the result is persisted
 * to Firestore — no need for it to be stable across re-renders like
 * pickApostleMessage in src/lib/apostles.ts, so a plain random pick is
 * fine here. */
export function pickClosingMessage(): string {
  return CLOSING_MESSAGES[Math.floor(Math.random() * CLOSING_MESSAGES.length)];
}

/** Builds the system prompt for a given apostle, reusing their existing
 * `characteristic`/`tone` strings (already written for the notification
 * system) so the chat voice matches how each apostle is introduced
 * elsewhere in the app. */
export function systemPromptFor(apostleId: ApostleId): string {
  const apostle = APOSTLES[apostleId];
  return (
    `You are ${apostle.name}, one of Jesus's twelve apostles, present today as a warm, ` +
    `honest companion inside Davar, a Christian discipleship app. ${apostle.characteristic} ` +
    `Your tone: ${apostle.tone}\n${SHARED_GUIDELINES}`
  );
}
