import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by @ducanh2912/next-pwa at build time.
    "public/sw.js",
    "public/workbox-*.js",
    "public/worker-*.js",
    "public/fallback-*.js",
    "public/swe-worker-*.js",
    // Runs in a ServiceWorkerGlobalScope, excluded from tsconfig.json for
    // the same reason (see its comment there) — type-aware lint rules
    // need a project that actually includes the file.
    "worker/**",
  ]),
]);

export default eslintConfig;
