import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { NextConfig } from "next";
import withPWAInit from "@ducanh2912/next-pwa";

// worker/index.ts (the custom service worker — see its own doc comment)
// needs the Firebase web config to call initializeApp(), but next-pwa
// compiles that file through a separate child webpack compiler that
// doesn't get Next's usual NEXT_PUBLIC_ env-var inlining (verified
// against its source — only its own __PWA_*__ constants are defined for
// that compilation), and fetching the config at runtime instead isn't
// safe either: a service worker must register its `push` listener
// synchronously during initial script evaluation, before any `await`
// resolves, or it can miss a push event that arrives while still
// loading. So this writes the config straight from process.env (already
// populated from .env.local by the time next.config.ts runs, same as
// any other Next.js env access) into a plain, gitignored module the
// worker imports like any other — sidestepping the inlining question
// entirely rather than fighting next-pwa's child compiler for it.
mkdirSync(join(process.cwd(), "worker"), { recursive: true });
writeFileSync(
  join(process.cwd(), "worker", "firebase-config.generated.ts"),
  `// Auto-generated by next.config.ts on every dev/build start — do not edit or commit (see worker/index.ts).\nexport const firebaseConfigForWorker = ${JSON.stringify(
    {
      apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY ?? "",
      authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN ?? "",
      projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID ?? "",
      messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID ?? "",
      appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID ?? "",
    },
    null,
    2,
  )};\n`,
);

// cacheOnFrontEndNav/aggressiveFrontEndNavCaching used to be turned on here
// (both default to false) — they cache every stylesheet/script fetched
// during client-side (next/link) navigation into a runtime cache separate
// from Workbox's normal per-build precache manifest, and that runtime
// cache isn't guaranteed to be invalidated the same way the precache is
// on a new deploy. In an app under active development, where a fresh
// deploy needs to actually show up, that trade-off isn't worth the
// snappier-feeling in-app navigation it buys — so back to the library's
// own defaults. skipWaiting/clientsClaim are already true by default
// (unset here on purpose), so a new service worker still takes over
// immediately on the next load rather than waiting for every tab to close.
const withPWA = withPWAInit({
  dest: "public",
  reloadOnOnline: true,
  disable: process.env.NODE_ENV === "development",
  workboxOptions: {
    disableDevLogs: true,
  },
});

const nextConfig: NextConfig = {
  /* config options here */
};

export default withPWA(nextConfig);
